# iDARTS 

Unlike some recent papers that have proposed regularization approaches for the DARTS, the iDARTS {cite:p}`zhang2021idarts` proposes a different way to compute the outer-loop gradient based on the implicit function theorem.<br> 

The Amended-DARTS {cite:p}`bi2020stabilizing` has actually arrived at the same outer-loop gradient (hypergradient) formula, stating that the gradient approximation in the original DARTS has been inaccurate. {cite:p}`bi2020stabilizing` have replaced the inverse Hessian with the Hessian itself in the formula to make computation more tractable however calculating the Hessian is still costly and it takes more time for the Amended-DARTS to reach optimality. Replacing the inverse Hessian within Hessian is also not a good approximation.

The iDARTS on the other hand, approximates the inverse Hessian and thus reduces the computational cost of the Amended-DARTS, as well as provides better results.

From the Original DARTS we had: <br>
$\nabla_\alpha L_{val} (w^*(a),a) \approx \nabla_\alpha L_{val} (w - \xi \nabla_w L_{train}(w,\alpha),a)$ <br>

Ideally, we'd want the $w - \xi \nabla_w L_{train}(w,\alpha)$ to be as close to the optimal $w^*(\alpha)$ as possible however this is very unlikely because as a result of the approximation the weights of the inner loop get updated only once.


However, if indeed $w ' = w - \xi \nabla_w L_{train}(w,\alpha)$ was optimal then we would have the training loss gradient $\nabla_{w} L_{train}(w^*,\alpha) = 0$ {cite:p}`zhang2021idarts`

Thus:<br>
$ \nabla^2_{w,\alpha} L_{train}(w^*,\alpha) = 0$<br>
$ \nabla_{w} (\nabla_{\alpha} L_{train}(w^*,\alpha)) = 0$<br>
$ \nabla_{w} (\nabla_{\alpha} L_{train}(w^*,\alpha) + \nabla_{w} L_{train}(w^*,\alpha). \nabla_{\alpha} w) = 0$<br>
$ \nabla^2_{w,\alpha} L_{train}(w^*,\alpha) + \nabla^2_{w,w} L_{train}(w^*,\alpha). \nabla_{\alpha} w = 0$<br>
$\nabla_{\alpha} w = - \big[\nabla^2_{w,w} L_{train}(w^*,\alpha)   \big]^{-1} . \nabla^2_{w,\alpha} L_{train}(w^*,\alpha)$<br>

Because the inverse Hessian of the training loss w.r.t the weights is expensive to compute the authors have proposed to use the Neumann approximation approach {cite:p}`DBLP:journals/corr/abs-1911-02590`
computed based on mini-batch samples. 

$\big[\nabla^2_{w,w} L_{train}(w^*,\alpha)   \big]^{-1} = \underset{i \to \infty}{lim} \overset{i}{\underset{j=0}{\sum}} \big[ I - \nabla^2_{w,w} L_{train}(w^*,\alpha) \big]^j    $

By using only the first K terms of the Neumann series:<br>
$\nabla_\alpha L_{val} (w',a) \approx \nabla_\alpha L_{val} (w' ,a) - \xi \nabla^2_{w\alpha} L_{train}(w,\alpha). \overset{K}{\underset{j=0}{\sum}} \big[ I - \xi \nabla^2_{w,w} L_{train}(w^*,\alpha) \big]^j  . \nabla_{w'} L_{val}(w',\alpha) \ \ \ \ $<br>

In [1]:
import numpy as np
from numpy.linalg import inv
from numpy import linalg as LA

In [2]:
N = 3
a = np.random.random((N,N))
b = inv(a)
np.max(LA.eig(a)[0]),b

(1.5273218780914237,
 array([[-0.32515194,  1.26840754, -0.23894487],
        [ 1.14430354, -0.4275755 , -0.20703836],
        [ 0.10063382, -0.53340203,  1.17050628]]))

In [3]:
N = 3
a = 100*np.random.random((N,N))
b = inv(a)
np.max(LA.eig(a)[0]),b

(124.74046442155341,
 array([[-0.0041333 , -0.00496709,  0.03683373],
        [ 0.00194555,  0.01385208, -0.02627344],
        [ 0.01030346, -0.00255451,  0.00413638]]))

In [4]:
N = 3
a = 10000*np.random.random((N,N))
b = inv(a)
np.max(LA.eig(a)[0]),b

(10722.79683739894,
 array([[ 7.19232029e-04,  1.07629930e-04, -1.45603628e-04],
        [ 1.94880340e-04, -2.02863249e-04,  2.35811275e-04],
        [-3.14699858e-04,  1.68092976e-04, -2.30566070e-05]]))

The larger the Hessian Norm, the smaller the inverse Hessian, so smaller step in that direction.

Determinant is product of eigenvalues https://math.berkeley.edu/~chenhi/math54-u15/problem150714.pdf.<br>
inv(A) = 1/det(A) . adj(A)<br>

Large eigenvalues (sharpness) > large determinant > smaller inverse matrix 